### ISSUE TITLE
Cards only on one side

### ISSUE THREAD

**Issue by AP2020C** [sominator/unity-2d-card-game-tutorial#3]
I am following the third video of your tutorial on youtube, after following the first two.
When I get to the first compilable point, about 1h10, and testable, I press in one part Host and the other Client, so I pressed the button to give the cards in the server, but also in the client in another attempt, but it only gave them in the player area. Whereas in the video it gives the cards to both players with one press of the button, in their own area.

I tried downloading and running the project from GitHub, but apart from being profoundly different, at least at this point, pressing the button did nothing!

By the way, I would have preferred that when you make tutorials you first declare variables and methods and then call them.

**Comment by sominator** [comment]
This sounds like an authority issue, or something else that is preventing the networking aspect of the game from working.  I'd recommend following the 2021 Update to this series (the link is in the description of the original tutorial, and the repo is available here: https://github.com/sominator/unity-2d-tabletop-multiplayer-2021-update).

You can also join us on Discord and share your code for one of us too look at.  Hope this helps!
